export const ranges = {
  'no-problems': [
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 71,
      lte: 130,
      color: '#58B711',
      label: 'No problems',
      code: 'glucose-fasting',
      severity_uid: 'no-problems',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 71,
      lte: 180,
      color: '#58B711',
      label: 'No problems',
      code: 'glucose-pos-meal',
      severity_uid: 'no-problems',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 71,
      lte: 130,
      color: '#58B711',
      label: 'No problems',
      code: 'glucose-pre-meal',
      severity_uid: 'no-problems',
    },
  ],
  light: [
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 131,
      lte: 140,
      color: '#A1B711',
      label: 'Light',
      code: 'glucose-fasting',
      severity_uid: 'light',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 181,
      lte: 200,
      color: '#A1B711',
      label: 'Light',
      code: 'glucose-pos-meal',
      severity_uid: 'light',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 131,
      lte: 180,
      color: '#A1B711',
      label: 'Light',
      code: 'glucose-pre-meal',
      severity_uid: 'light',
    },
  ],
  important: [
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 141,
      lte: 180,
      color: '#E6D10F',
      label: 'Important',
      code: 'glucose-fasting',
      severity_uid: 'important',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 201,
      lte: 260,
      color: '#E6D10F',
      label: 'Important',
      code: 'glucose-pos-meal',
      severity_uid: 'important',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 181,
      lte: 220,
      color: '#E6D10F',
      label: 'Important',
      code: 'glucose-pre-meal',
      severity_uid: 'important',
    },
  ],
  significant: [
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 181,
      lte: 250,
      color: '#E49421',
      label: 'Significant',
      code: 'glucose-fasting',
      severity_uid: 'significant',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 51,
      lte: 70,
      color: '#E49421',
      label: 'Significant',
      code: 'glucose-fasting',
      severity_uid: 'significant',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 261,
      lte: 360,
      color: '#E49421',
      label: 'Significant',
      code: 'glucose-pos-meal',
      severity_uid: 'significant',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 51,
      lte: 70,
      color: '#E49421',
      label: 'Significant',
      code: 'glucose-pos-meal',
      severity_uid: 'significant',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 221,
      lte: 250,
      color: '#E49421',
      label: 'Significant',
      code: 'glucose-pre-meal',
      severity_uid: 'significant',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 51,
      lte: 70,
      color: '#E49421',
      label: 'Significant',
      code: 'glucose-pre-meal',
      severity_uid: 'significant',
    },
  ],
  urgent: [
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 251,
      lte: null,
      color: '#CA1930',
      label: 'Urgent',
      code: 'glucose-fasting',
      severity_uid: 'urgent',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: null,
      lte: 50,
      color: '#CA1930',
      label: 'Urgent',
      code: 'glucose-fasting',
      severity_uid: 'urgent',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 361,
      lte: null,
      color: '#CA1930',
      label: 'Urgent',
      code: 'glucose-pos-meal',
      severity_uid: 'urgent',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: null,
      lte: 50,
      color: '#CA1930',
      label: 'Urgent',
      code: 'glucose-pos-meal',
      severity_uid: 'urgent',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: 251,
      lte: null,
      color: '#CA1930',
      label: 'Urgent',
      code: 'glucose-pre-meal',
      severity_uid: 'urgent',
    },
    {
      lt: null,
      gt: null,
      eq: null,
      gte: null,
      lte: 50,
      color: '#CA1930',
      label: 'Urgent',
      code: 'glucose-pre-meal',
      severity_uid: 'urgent',
    },
  ],
};

export const readingsRanges = [
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 71,
    lte: 130,
    color: '#58B711',
    label: 'No problems',
    code: 'glucose-fasting',
    severity_uid: 'no-problems',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 131,
    lte: 140,
    color: '#A1B711',
    label: 'Light',
    code: 'glucose-fasting',
    severity_uid: 'light',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 141,
    lte: 180,
    color: '#E6D10F',
    label: 'Important',
    code: 'glucose-fasting',
    severity_uid: 'important',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 181,
    lte: 250,
    color: '#E49421',
    label: 'Significant',
    code: 'glucose-fasting',
    severity_uid: 'significant',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 51,
    lte: 70,
    color: '#E49421',
    label: 'Significant',
    code: 'glucose-fasting',
    severity_uid: 'significant',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 251,
    lte: null,
    color: '#CA1930',
    label: 'Urgent',
    code: 'glucose-fasting',
    severity_uid: 'urgent',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: null,
    lte: 50,
    color: '#CA1930',
    label: 'Urgent',
    code: 'glucose-fasting',
    severity_uid: 'urgent',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 71,
    lte: 180,
    color: '#58B711',
    label: 'No problems',
    code: 'glucose-pos-meal',
    severity_uid: 'no-problems',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 181,
    lte: 200,
    color: '#A1B711',
    label: 'Light',
    code: 'glucose-pos-meal',
    severity_uid: 'light',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 201,
    lte: 260,
    color: '#E6D10F',
    label: 'Important',
    code: 'glucose-pos-meal',
    severity_uid: 'important',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 261,
    lte: 360,
    color: '#E49421',
    label: 'Significant',
    code: 'glucose-pos-meal',
    severity_uid: 'significant',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 51,
    lte: 70,
    color: '#E49421',
    label: 'Significant',
    code: 'glucose-pos-meal',
    severity_uid: 'significant',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 361,
    lte: null,
    color: '#CA1930',
    label: 'Urgent',
    code: 'glucose-pos-meal',
    severity_uid: 'urgent',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: null,
    lte: 50,
    color: '#CA1930',
    label: 'Urgent',
    code: 'glucose-pos-meal',
    severity_uid: 'urgent',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 71,
    lte: 130,
    color: '#58B711',
    label: 'No problems',
    code: 'glucose-pre-meal',
    severity_uid: 'no-problems',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 131,
    lte: 180,
    color: '#A1B711',
    label: 'Light',
    code: 'glucose-pre-meal',
    severity_uid: 'light',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 181,
    lte: 220,
    color: '#E6D10F',
    label: 'Important',
    code: 'glucose-pre-meal',
    severity_uid: 'important',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 221,
    lte: 250,
    color: '#E49421',
    label: 'Significant',
    code: 'glucose-pre-meal',
    severity_uid: 'significant',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 51,
    lte: 70,
    color: '#E49421',
    label: 'Significant',
    code: 'glucose-pre-meal',
    severity_uid: 'significant',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: 251,
    lte: null,
    color: '#CA1930',
    label: 'Urgent',
    code: 'glucose-pre-meal',
    severity_uid: 'urgent',
  },
  {
    lt: null,
    gt: null,
    eq: null,
    gte: null,
    lte: 50,
    color: '#CA1930',
    label: 'Urgent',
    code: 'glucose-pre-meal',
    severity_uid: 'urgent',
  },
];
